apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gcp-simulation
  labels:
    app: shopsphere-frontend
spec:
  selector:
    app: shopsphere-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
