apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gcp-simulation
  labels:
    app: shopsphere-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-frontend
  template:
    metadata:
      labels:
        app: shopsphere-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: frontend-config
